# Generated by Django 4.1.1 on 2022-09-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_stacks', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ShowService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_desc', models.CharField(max_length=200)),
                ('service_icon', models.CharField(max_length=100)),
                ('service_box_svg', models.CharField(max_length=5000)),
                ('service_iconbox_color', models.CharField(max_length=100)),
            ],
        ),
    ]
