# Generated by Django 4.1.1 on 2022-09-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceStack',
        ),
    ]
