# Generated by Django 4.1.1 on 2022-09-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0003_servicestack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceStack',
        ),
    ]
