# Generated by Django 4.1.1 on 2022-09-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0005_servicestack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicestack',
            old_name='service_icon_color',
            new_name='service_stacks_icons_color',
        ),
    ]
