# Generated by Django 4.1.1 on 2022-09-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0006_rename_service_icon_color_servicestack_service_stacks_icons_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('fb', models.URLField(blank=True)),
                ('lnkd', models.URLField(blank=True)),
                ('twt', models.URLField(blank=True)),
                ('insta', models.URLField(blank=True)),
                ('sample', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='servicestack',
            name='service_stacks_icons_color',
            field=models.CharField(max_length=300),
        ),
    ]
