# Generated by Django 4.1.1 on 2022-09-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0007_teammember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
