# Generated by Django 4.1.1 on 2022-09-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0008_alter_teammember_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='fb',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='insta',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='lnkd',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='twt',
            new_name='twitter',
        ),
    ]
