# Generated by Django 4.1.1 on 2022-09-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0009_rename_fb_teammember_facebook_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
