# Generated by Django 4.1.1 on 2022-09-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0010_delete_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='teamPhotos')),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('sample', models.URLField(blank=True)),
            ],
        ),
    ]
