# Generated by Django 4.1.1 on 2022-09-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0011_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
