# Generated by Django 4.1.1 on 2022-09-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0013_alter_subscription_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
    ]
